//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EStore.Shared.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;



    public partial class eccomerence_storeContext : DbContext
    {
        

        public eccomerence_storeContext() : base(@"Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=eccomerence_store;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False")
        {


        }
        //protected override void OnModelCreating(DbModelBuilder modelBuilder)
        //{
          //  throw new UnintentionalCodeFirstException();
        //}

        public virtual DbSet<User> Users{ get ; set; }
        public virtual DbSet<Role> Roles{ get; set; }



    }
    //partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}

